sonar.projectKey=GUISkinDose
sonar.projectName=GUISkinDose
sonar.sourceEncoding=UTF-8
sonar.sources=src,scripts
sonar.tests=tests
sonar.python.version=3.10,3.11,3.12,3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,src/**/example_data/**,src/**/phantom_data/**,src/**/table_data/**
sonar.test.exclusions=tests/fixtures/**
sonar.coverage.exclusions=tests/**,scripts/**
