#!/usr/bin/env python3
"""Render/check the human-readable sensitive-asset review inventory.

``dev-docs/approved_asset_inventory.json`` remains the machine-readable source
of truth for the admission gate. This tool renders that data as Markdown with
repository-relative links, preventing a second hand-maintained inventory from
drifting. Use ``--write`` after changing the JSON and ``--check`` in CI.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence
from urllib.parse import quote

try:
    from scripts.check_sensitive_content import INVENTORY_RELATIVE_PATH, load_inventory, repo_root_from_script
except ModuleNotFoundError:  # Direct ``python scripts/render_asset_inventory.py`` execution.
    from check_sensitive_content import INVENTORY_RELATIVE_PATH, load_inventory, repo_root_from_script


MARKDOWN_RELATIVE_PATH = Path("dev-docs/approved_asset_inventory.md")
KIND_LABELS = {
    "dicom": "DICOM",
    "archive": "Archive",
    "extensionless": "Extensionless",
    "image": "Image",
    "notebook_embedded_visual": "Notebook embedded visual",
    "opaque_binary": "Opaque binary",
    "office_document": "Office/iWork document",
    "pdf": "PDF",
    "postscript": "PostScript/EPS",
}


def _escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _asset_link(path: str) -> str:
    destination = quote(f"../{path}", safe="/._-")
    return f"[`{_escape_cell(path)}`]({destination})"


def _review_status(entry: dict[str, object]) -> str:
    review = entry.get("review")
    if not isinstance(review, dict):
        return "⚠ Missing review metadata"
    status = review.get("status")
    if status == "approved":
        reviewer = _escape_cell(review.get("reviewer") or "reviewer not recorded")
        reviewed_on = _escape_cell(review.get("reviewed_on") or "date not recorded")
        return f"✅ Approved — {reviewer} ({reviewed_on})"
    if status == "pending":
        return "⏳ Pending manual review"
    return f"⚠ Unknown status: `{_escape_cell(status)}`"


def _review_checklist(entry: dict[str, object]) -> str:
    kind = entry.get("kind")
    if kind == "dicom":
        review = entry.get("dicom_review")
        if not isinstance(review, dict):
            return "⚠ Missing DICOM checklist"
        checks = (
            ("IDs", "direct_identifiers_reviewed"),
            ("private", "private_tags_reviewed"),
            ("pixels", "burned_in_text_reviewed"),
        )
    elif kind in {"archive", "office_document"}:
        review = entry.get("container_review")
        if not isinstance(review, dict):
            return "⚠ Missing container checklist"
        checks = (
            ("files", "embedded_files_reviewed"),
            ("images", "embedded_images_reviewed"),
            ("DICOM", "embedded_dicom_reviewed"),
        )
    elif kind == "notebook_embedded_visual":
        review = entry.get("notebook_review")
        if not isinstance(review, dict):
            return "⚠ Missing notebook checklist"
        checks = (
            ("images", "embedded_images_reviewed"),
            ("burned-in", "burned_in_text_reviewed"),
        )
    else:
        return "—"
    if not isinstance(review, dict):
        return "⚠ Missing review checklist"
    return " · ".join(f"{label} {'✓' if review.get(key) is True else '☐'}" for label, key in checks)


def render_inventory_markdown(repo_root: Path) -> str:
    """Return deterministic Markdown for the JSON inventory in repository order."""
    entries = load_inventory(repo_root / INVENTORY_RELATIVE_PATH)
    lines = [
        "# Sensitive asset review inventory",
        "",
        "<!-- Generated by scripts/render_asset_inventory.py from approved_asset_inventory.json; do not edit by hand. -->",
        "",
        "This is the human-friendly view of the machine-enforced inventory. Review the linked asset, record the",
        "reviewer/date and required DICOM checklist in",
        "[`approved_asset_inventory.json`](approved_asset_inventory.json), then regenerate this file with:",
        "",
        "```bash",
        "python scripts/render_asset_inventory.py --write",
        "```",
        "",
        "The admission gate verifies each full SHA-256 value in the JSON. The table shows a short prefix only to make",
        "human review practical. `⏳` is not approval; `✅` means the recorded reviewer manually cleared that exact",
        "file revision.",
        "",
        f"**Assets tracked:** {len(entries)}",
        "",
        "| Asset | Type | Purpose | Manual review | Review checklist | SHA-256 prefix |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for path, entry in entries.items():
        kind = KIND_LABELS.get(str(entry.get("kind")), _escape_cell(entry.get("kind", "unknown")))
        purpose = _escape_cell(entry.get("purpose", ""))
        digest = _escape_cell(entry.get("sha256", ""))[:12]
        lines.append(
            f"| {_asset_link(path)} | {kind} | {purpose} | {_review_status(entry)} | "
            f"{_review_checklist(entry)} | `{digest}` |"
        )
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=repo_root_from_script())
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--check", action="store_true", help="Fail if the Markdown view is missing or stale.")
    action.add_argument("--write", action="store_true", help="Rewrite the Markdown view from the JSON inventory.")
    action.add_argument("--print", action="store_true", help="Print the generated Markdown without writing it.")
    args = parser.parse_args(argv)
    repo_root = args.repo_root.resolve()
    output_path = repo_root / MARKDOWN_RELATIVE_PATH
    try:
        rendered = render_inventory_markdown(repo_root)
    except ValueError as exc:
        print(f"render_asset_inventory: {exc}", file=sys.stderr)
        return 2

    if args.print:
        print(rendered, end="")
        return 0
    if args.write:
        output_path.write_text(rendered, encoding="utf-8")
        return 0
    try:
        current = output_path.read_text(encoding="utf-8")
    except OSError:
        current = ""
    if current != rendered:
        print(
            "Sensitive asset inventory Markdown is missing or stale; "
            "run: python scripts/render_asset_inventory.py --write",
            file=sys.stderr,
        )
        return 1
    print("Sensitive asset inventory Markdown is current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
